### ISSUE TITLE
严大，  是否考虑一下  适配全面屏手机，三星S8，小米Mix等

### ISSUE THREAD

**Issue by DevXue** [yanzhenjie/Sofia#10]
在全面屏手机上使用这个库，底部出现大片的白边，例如三星S8， 小米Mix 都会有这情况，大神是否考虑适配一下呢！谢谢

**Comment by yanzhenjie** [comment]
如果你使用了Sofia，要设置颜色的。建议是普通颜色，直接用系统的Theme指定状态栏颜色即可，如果用到侵入状态栏、导航栏效果时再使用Sofia。

**Comment by DevXue** [comment]
我现在就是使用的你的Sofia这个库，  设置颜色，状态栏是白色以及字体颜色也是白色的。
除了全面屏手机外，其他手机效果挺好的，但就是全面屏底部会出现大白边，很不好看，  还有大神你说的   如果使用了侵入状态栏，导航栏效果时在使用Sofia 是啥意思？？？  我在BaseActivity中使用 Sofia.with(this).statusBarDarkFont();，让所有Activity实现这个效果
color.xml 
 <color name="colorPrimary">@color/white</color>
    <color name="colorPrimaryDark">@color/white</color>
    <color name="colorAccent">#FF9900</color>
就这么写的， 其他啥也没干！

**Comment by yanzhenjie** [comment]
使用了Sofia就必须要指定状态栏颜色和导航栏颜色，不然就是透明色（显示底层View颜色，例如白色或者黑色）。

**Comment by DevXue** [comment]
你说的这个导航栏颜色是不是华为那个  虚拟导航栏？？？

**Comment by yanzhenjie** [comment]
就是有仨虚拟键的那个底部导航栏，很多手机都有。

**Comment by DevXue** [comment]
嗯嗯，   谢谢 严大。   那我是不是应该设置成透明呢？  为了不让那大白边出现？

**Comment by yanzhenjie** [comment]
一般是黑色或者灰黑色吧，看看Sofia主页上的效果。你需要啥色或者图片就设置啥。

**Comment by DevXue** [comment]
谢谢，  我下午找同事的三星S8试试！

**Comment by HaoTianhua** [comment]
@yanzhenjie 严大，但这么设置后并没有达到适配全面屏的效果啊。例小米MIX手机在设置了支持全面屏后，虚拟按键（即底部有三个东西的那块）隐藏起来了。但该出区域并没有被利用起来。应用并没有达到实际的底部位置啊~

**Comment by yanzhenjie** [comment]
如果是全面屏就调用`invasionNavigationBar()`入侵导航栏，就会占据底部了。当然非全面屏也可以调用这个方法，但是底部的三个按键还是悬浮在我们的App上面的。

另外我这边小米都是物理见，没法测试虚拟键并设置全面屏的情况，你把判断全面屏的Api贴出来一下，下个版本我在内部也适配一下。

**Comment by PeanutZhang** [comment]
手动隐藏虚拟导航栏后，如何去掉占位的view呢
