### ISSUE TITLE
使用这个库会导致有webview问题

### ISSUE THREAD

**Issue by lany192** [yanzhenjie/Sofia#11]
问题：如果某个界面使用了webview，弹窗输入法后会遮住webview上的输入框，但webview不能滚动

**Comment by lany192** [comment]
就是库中使用的View.SYSTEM_UI_FLAG_FULLSCREEN会和webview滚动冲突

**Comment by yanzhenjie** [comment]
其实一般直接用系统的Theme指定状态栏颜色就好了。使用侵入状态栏或者导航栏的功能时再使用Safia就好了，一般比如产品详情页（歌曲、商品、店铺、图片浏览）。

**Comment by yanzhenjie** [comment]
No responed, close.
