### ISSUE TITLE
严大，报错了  ClassNotFoundException ？

### ISSUE THREAD

**Issue by DevXue** [yanzhenjie/Sofia#16]
看到Bugly上面显示的 说是：ClassNotFoundException  ，手机型号也给出了 说是华为荣耀 PRA AL00X   Android7.0 ，应该是客户使用过程中报的错  上传到了Bugly了 ，今天看到了这个错  但是不知道咋回事，还请严大看看，这是什么引起的呢？
![1](https://user-images.githubusercontent.com/9455329/37069715-89a6fcd2-21ef-11e8-9759-10b2d482233a.png)
![2](https://user-images.githubusercontent.com/9455329/37069718-8ea228ba-21ef-11e8-9e8f-d32ec5baa7ef.png)

**Comment by yanzhenjie** [comment]
这种错一般和第三方库无关。我们一般可以从64k问题入手查，网络上也有一些上述异常相关的排查博文可以借鉴一下。
