### ISSUE TITLE
严大，底部虚拟按键收起后黑色背景没有被收起，如下图

### ISSUE THREAD

**Issue by ejwdhr** [yanzhenjie/Sofia#18]
![screenshot_2018-03-13-09-37-44](https://user-images.githubusercontent.com/19422579/37317921-8853d096-26a2-11e8-8196-545f888a1e04.png)

**Comment by ejwdhr** [comment]
可不可以增加一个移除添加底部view的方法，这样就可以通过监听底部虚拟按键隐藏显示这个view

**Comment by PeanutZhang** [comment]
这个问题 我也遇到了 ， 请问你如何解决的
