### ISSUE TITLE
小米6上设置状态栏灰色文字无效果

### ISSUE THREAD

**Issue by miaoyongjun** [yanzhenjie/Sofia#2]
小米6上设置状态栏灰色文字无效果
达哥有时间可以测试一下

**Comment by lliuguangbo** [comment]
miui版本是不是7.7.13以上，从7.7.13开始，miui重新适配回Android官方的api

**Comment by lliuguangbo** [comment]
https://dev.mi.com/console/doc/detail?pId=1159

**Comment by yanzhenjie** [comment]
更新了v1.0.4，修复了这个问题，优化了Api。  
从1.0.4版本开始本项目改名为Sofia，由于原来的名字不太适合链式调用，于是我顺便换了一个相对优雅的名字：Sofia，译为中文大概可叫做：索菲亚。Sofia一词源自于希腊语∑οφία，含义为智慧，这也是我赋予这个项目的愿望。
