### ISSUE TITLE
华为 CHM- TL00  android4.4.2 全部跪了，没任何侵入效果

### ISSUE THREAD

**Issue by yongchao1210** [yanzhenjie/Sofia#4]
华为荣耀畅玩4C 
型号： CHM- TL00  
系统版本：Android4.4.2 
全部跪了，没任何侵入效果
（直接运行demo代码，未改动）

**Comment by lliuguangbo** [comment]
没适配4.4.2， 5.0以上有效

**Comment by yongchao1210** [comment]
@lliuguangbo 只有android5.0以上的才有效吗？

**Comment by lliuguangbo** [comment]
@yongchao1210 对的，看源码是只支持5.0以上。

**Comment by yongchao1210** [comment]
@lliuguangbo 那就不爽了 现在5.0以下的手机好不少的

**Comment by lliuguangbo** [comment]
@yongchao1210 你可以自己适配，代码量也不多; 其实4.4的效果与5.0的效果还是有点不同，4.4的有层东西在
