### ISSUE TITLE
状态栏和导航栏不能可选配置

### ISSUE THREAD

**Issue by yezhichao** [yanzhenjie/Sofia#8]
你好，
如果我只是想要状态栏的效果，但是在返回HostLayout的时候直接去设置了导航栏的透明，我并不能控制。

如果为了达到一致的效果调用Sofia.with(this).navigationBarBackground(color(android.R.color.black))把状态栏设置成黑色，在横屏状态下会导致底部多一块黑色的view。

建议可以在with之后配置一些可选参数，以屏蔽部分功能

**Comment by yanzhenjie** [comment]
好建议，我尽快。

**Comment by leleliu008** [comment]
是的，华为的大部分手机有导航栏，而且导航栏是可以收起的，一旦收起了，NavigationView还在显示，这个问题要么设置一个开关，把导航栏的功能屏蔽掉，要么也可以实现导航栏显示和隐藏的监听。可以通过activityRootView.getViewTreeObserver().addOnGlobalLayoutListener(newOnGlobalLayoutListener())来实现，但是它要必须设置为resize模式，我看到华为手机会发出状态栏改变的广播，也可以这么实现。
